Recipes: {
    "ENCHANTED_GOLDEN_APPLE": {
        1: "BLAZE_POWDER",
        2: "GOLD_BLOCK",
        3: "BLAZE_POWDER",
        4: "GOLD_BLOCK",
        5: "APPLE",
        6: "GOLD_BLOCK",
        7: "BLAZE_POWDER",
        8: "GOLD_BLOCK",
        9: "BLAZE_POWDER"
    },
    "IRON_HORSE_ARMOR": {
        1: "IRON_INGOT",
        2: "IRON_INGOT",
        3: "IRON_INGOT",
        4: "IRON_INGOT",
        5: "LEATHER_HORSE_ARMOR",
        6: "IRON_INGOT",
        7: "IRON_INGOT",
        8: "IRON_INGOT",
        9: "IRON_INGOT"
    },
    "GOLDEN_HORSE_ARMOR": {
        1: "GOLD_INGOT",
        2: "GOLD_INGOT",
        3: "GOLD_INGOT",
        4: "GOLD_INGOT",
        5: "LEATHER_HORSE_ARMOR",
        6: "GOLD_INGOT",
        7: "GOLD_INGOT",
        8: "GOLD_INGOT",
        9: "GOLD_INGOT"
    },
    "DIAMOND_HORSE_ARMOR": {
        1: "DIAMOND",
        2: "DIAMOND",
        3: "DIAMOND",
        4: "DIAMOND",
        5: "LEATHER_HORSE_ARMOR",
        6: "DIAMOND",
        7: "DIAMOND",
        8: "DIAMOND",
        9: "DIAMOND"
    },
    "SADDLE": {
        1: "AIR",
        2: "AIR",
        3: "AIR",
        4: "LEATHER",
        5: "LEATHER",
        6: "LEATHER",
        7: "STRING",
        8: "IRON_INGOT",
        9: "STRING"
    }
}